#!/usr/bin/env bash
set -euo pipefail

DCM_OWL_ENDPOINT="ftp://medical.nema.org/medical/dicom/resources/ontology/dcm/dcm.owl"
NOW="$(date -Iseconds)"
TARGET_DIR="/ttl-static"
TARGET_FILE="$TARGET_DIR/dcm-concept-code-labels.ttl"

mkdir -p "$TARGET_DIR"
echo "# Autogenerated on $NOW via \`$0\`." >"$TARGET_FILE"
curl -s --disable-epsv "$DCM_OWL_ENDPOINT" |
    xq -r '
."rdf:RDF"."rdf:Description"[]
| select(
    ."skos:notation"."#text"
    and ."skos:prefLabel"."#text"
    and ."skos:prefLabel"."@xml:lang"
    and ."skos:definition"."#text"
    and ."skos:definition"."@xml:lang"
  )
| {
    notation: ."skos:notation"."#text",
    label: ."skos:prefLabel"."#text",
    labelLang: ."skos:prefLabel"."@xml:lang",
    definition: ."skos:definition"."#text",
    definitionLang: ."skos:definition"."@xml:lang"
  }
| "<https://dicom.nema.org/resources/ontology/DCM/\(.notation)> <http://www.w3.org/2000/01/rdf-schema#label> \(.label|@json)@\(.labelLang) .\n<https://dicom.nema.org/resources/ontology/DCM/\(.notation)> <http://www.w3.org/2000/01/rdf-schema#comment> \(.definition|@json)@\(.definitionLang) ."
' | sort >>"$TARGET_FILE"
