#!/usr/bin/env bash
set -euo pipefail

ATTRIBUTES_JSON_ENDPOINT="https://raw.githubusercontent.com/innolitics/dicom-standard/refs/heads/master/standard/attributes.json"
NOW="$(date -Iseconds)"
TARGET_DIR="/ttl-static"
TARGET_FILE="$TARGET_DIR/dcm-tag-labels.ttl"

mkdir -p "$TARGET_DIR"
echo "# Autogenerated on $NOW via \`$0\`." >"$TARGET_FILE"
curl -s "$ATTRIBUTES_JSON_ENDPOINT" |
    jq -r '.[] | "<http://dicom2rdf.uniklinik-freiburg.de/\(.id | ascii_upcase)> <http://www.w3.org/2000/01/rdf-schema#label> \"\(.name)\"@en ."' |
    sort >>"$TARGET_FILE"
