#!/usr/bin/env bash
set -euo pipefail

NOW="$(date -Iseconds)"
STANDARD_SOP_CLASSES_ENDPOINT="https://dicom.nema.org/dicom/2013/output/chtml/part04/sect_B.5.html"
TARGET_DIR="/ttl-static"
TARGET_FILE="$TARGET_DIR/sop-class-uid-labels.ttl"

mkdir -p "$TARGET_DIR"
echo "# Autogenerated on $NOW via \`$0\`." >"$TARGET_FILE"
curl -s "$STANDARD_SOP_CLASSES_ENDPOINT" |
    xmllint --html --xpath "//table[@frame='box' and @rules='all']/tbody/tr/td[position()<=2]/p/text()" - 2>/dev/null |
    awk '
function trim(s) {
  gsub(/^[[:space:]]+|[[:space:]]+$/, "", s);
  return s;
}
NR % 2 == 1 {
  label = trim($0);
  next;
}
{
  oid = trim($0);
  if (label != "" && oid != "") {
    printf "<urn:oid:%s> <http://www.w3.org/2000/01/rdf-schema#label> \"%s\"@en .\n", oid, label;
  }
}
' | sort >>"$TARGET_FILE"
